### ISSUE TITLE
Can't use it on Ubuntu 18.04.6 LTS

### ISSUE THREAD

**Issue by cheretbe** [abbbi/nullfsvfs#15]
Hi @abbbi
First of all, thank you for this great project! Occasionally it helps me to tackle network issues.
Today I tried to use it once again and encountered the following problem.
```
# uname -a
Linux homemain 4.15.0-192-generic #203-Ubuntu SMP Wed Aug 10 17:40:03 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
# make -C /lib/modules/$(uname -r)/build M=$PWD modules_install INSTALL_MOD_DIR=kernel/fs/nullfs
make: Entering directory '/usr/src/linux-headers-4.15.0-192-generic'
  DEPMOD  4.15.0-192-generic
make: Leaving directory '/usr/src/linux-headers-4.15.0-192-generic'
# depmod
# modprobe  nullfs
modprobe: FATAL: Module nullfs not found in directory /lib/modules/4.15.0-192-generic
```
Tried both 0.12.1 and master branch.
Do you have any suggestions?

**Comment by abbbi** [comment]
likely an issue with the modules installation path. check where it was installed in /lib/modules.
otherwise simply load directly using insmod

on ubuntu its probably better you build via dpkg-buildpackage, see: https://github.com/abbbi/nullfsvfs#debian-package

**Comment by cheretbe** [comment]
`/lib/modules/4.15.0-192-generic/kernel/fs/nullfs/` was empy. Manual copying of `nullfs.ko` solved the issue.
Thanks for the help :handshake:
