### ISSUE TITLE
Unable to build package it on Ubuntu 22.04 server

### ISSUE THREAD

**Issue by caobo1994** [abbbi/nullfsvfs#23]
When I build the deb package in the server, it says

root@localhost:~/nullfsvfs-0.17# dpkg-buildpackage -r fakeroot
dpkg-buildpackage: error: unknown option or argument fakeroot

Use --help for program usage information.

I then tried the following command and it says

dpkg-buildpackage: info: source package nullfsvfs
dpkg-buildpackage: info: source version 0.17
dpkg-buildpackage: info: source distribution unstable
dpkg-buildpackage: info: source changed by Michael Ablassmeier <abi@debian.org>
dpkg-buildpackage: info: host architecture amd64
 dpkg-source --before-build .
 debian/rules clean
dh clean --with dkms
   dh_auto_clean
	make -j1 clean
make[1]: Entering directory '/root/nullfsvfs-0.17'
make -C /lib/modules/5.15.0-91-generic/build M=/root/nullfsvfs-0.17 clean
make[2]: Entering directory '/usr/lib/modules/5.15.0-91-generic/build'
ls
Makefile
make[2]: Leaving directory '/usr/lib/modules/5.15.0-91-generic/build'
make[1]: Leaving directory '/root/nullfsvfs-0.17'
   dh_clean
 dpkg-source -b .
dpkg-source: info: using source format '3.0 (native)'
dpkg-source: info: building nullfsvfs in nullfsvfs_0.17.tar.xz
dpkg-source: info: building nullfsvfs in nullfsvfs_0.17.dsc
 debian/rules build
dh build --with dkms
   dh_update_autotools_config
   dh_autoreconf
   dh_auto_configure
   dh_auto_build
	make -j1
make[1]: Entering directory '/root/nullfsvfs-0.17'
make -C /lib/modules/5.15.0-91-generic/build M=/root/nullfsvfs-0.17 modules
make[2]: Entering directory '/usr/lib/modules/5.15.0-91-generic/build'
make[2]: *** No rule to make target 'modules'.  Stop.
make[2]: Leaving directory '/usr/lib/modules/5.15.0-91-generic/build'
make[1]: *** [Makefile:5: ko] Error 2
make[1]: Leaving directory '/root/nullfsvfs-0.17'
dh_auto_build: error: make -j1 returned exit code 2
make: *** [debian/rules:6: build] Error 2
dpkg-buildpackage: error: debian/rules build subprocess returned exit status 2

Could you help me solve it? Thanks!

**Comment by abbbi** [comment]
I think you Need to install Kernel-Headers Package for the Kernel Version bootet

**Comment by joshjowen** [comment]
The instructions in the readme are missing some things. Try `apt-get install debhelper dkms dh-dkms` (You also need dh-dkms) then `dpkg-buildpackage -uc -us -rfakeroot` (no space between -r and fakeroot, also probably don't want to sign the package)

**Comment by abbbi** [comment]
@joshjowen thanks, updated.
