### ISSUE TITLE
recent addition for uid/gid breaks backwards compatibility

### ISSUE THREAD

**Issue by ricksustek** [abbbi/nullfsvfs#5]
On the master branch, the change to nullfs.c to allow for specifying a specific uid or gid in the mount options, breaks things a bit! The code will now default to using root uid/gid when new inodes are created. Previous code allowed for the uid/gid fields of the new inode to be that of the user creating the file. Seems like some conditional code is needed to restore beauty.

**Comment by abbbi** [comment]
Should be fixed.
